--
-- PostgreSQL database dump
--
create database centros;
\c centros

-- Dumped from database version 14.9 (Homebrew)
-- Dumped by pg_dump version 14.9 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acerca; Type: TABLE; Schema: public; Owner: userdatabase
--

CREATE TABLE public.acerca (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(191) NOT NULL,
    descripcion varchar(191),
    contenido varchar(4000) NOT NULL,
    visible integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

CREATE TABLE public.archivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
    imagen integer NOT NULL,
    url varchar(191) NOT NULL,    
    name_imagen varchar(191) NOT NULL
    descripcion varchar(400) NOT NULL,
    activo integer NOT NULL,   
    estado integer NOT NULL, 
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
);



CREATE TABLE public.centros (
    centro bigint NOT NULL,
    nombre varchar(400) NOT NULL,
    departamento varchar(191),
    municipio varchar(191),
    direccion varchar(191),
    telefono varchar(191),
    encargado varchar(191),
    email varchar(191),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


CREATE TABLE public.cursos (    
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Carrera varchar(191) NOT NULL,
    Nombre_Curso varchar(191) NOT NULL,
    Curso varchar(191) NOT NULL,
    Seccion varchar(191) NOT NULL,
    Tipoasig varchar(191) NOT NULL,
    Periodo varchar(191) NOT NULL,
    Pensum varchar(191) NOT NULL,
    Ciclo varchar(191) NOT NULL,
    No_Asignados varchar(191) NOT NULL,
    centro integer NOT NULL,
    Jornada varchar(191) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    desc_seccion varchar(191) NOT NULL,
    inicio date,
    fin date
);




CREATE TABLE public.especialidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Carrera varchar(10) NOT NULL,
    Pensum varchar(14) NOT NULL,
    Nombre varchar(200) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);



CREATE TABLE public.horarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso varchar(191) NOT NULL,
    carrera varchar(191) NOT NULL,
    seccion varchar(191) NOT NULL,
    tipoasig varchar(191) NOT NULL,
    portal varchar(191) NOT NULL,
    periodo varchar(191) NOT NULL,
    dia varchar(191) NOT NULL,
    horaini timestamp(0) without time zone NOT NULL,
    horafin timestamp(0) without time zone NOT NULL,
    correlativo integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);



CREATE TABLE public.informacion_academica (    
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    nombre varchar(100) NOT NULL,
    icono varchar(50) NOT NULL,
    descripcion varchar(500) NOT NULL,
    vence timestamp(0) without time zone,
    url varchar(191) NOT NULL
);


CREATE TABLE public.migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration varchar(191) NOT NULL,
    batch integer NOT NULL
);


CREATE TABLE public.model_has_permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    model_type varchar(191) NOT NULL,
    model_id bigint NOT NULL
);


CREATE TABLE public.model_has_roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_type varchar(191) NOT NULL,
    model_id bigint NOT NULL
);

CREATE TABLE public.noticias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(191) NOT NULL,
    descripcion varchar(191),
    contenido varchar(4000) NOT NULL,
    visible integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


CREATE TABLE public.password_resets (
    email varchar(191) NOT NULL,
    token varchar(191) NOT NULL,
    created_at timestamp(0) without time zone
);


CREATE TABLE public.periodos (
    carrera varchar(191) NOT NULL,
    periodo varchar(191) NOT NULL,
    descripcion varchar(191) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


CREATE TABLE public.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(191) NOT NULL,
    guard_name varchar(191) NOT NULL,
    title varchar(191) NOT NULL,
    description varchar(191) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

--

CREATE TABLE public.preguntas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    pregunta varchar(191) NOT NULL,
    respuesta varchar(4000) NOT NULL,
    visible integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


--

CREATE TABLE public.role_has_permissions (
    permission_id  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL
);


CREATE TABLE public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(191) NOT NULL,
    guard_name varchar(191) NOT NULL,
    title varchar(191) NOT NULL,
    description varchar(191) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);



CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(191) NOT NULL,
    email varchar(191) NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password varchar(191) NOT NULL,
    remember_token varchar(100),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

--

COPY public.acerca (id, titulo, descripcion, contenido, visible, created_at, updated_at) FROM stdin;
1	UNIVERSIDAD GALILEO	Información a mostrar	<p class="ql-align-justify">Consciente de los desafíos a los que se enfrenta el nivel&nbsp;educativo superior, y convencida de las oportunidades que la educación abierta ofrece a personas que no tienen acceso a una educación superior y en respuesta a la creciente demanda de servicios educativos, creó el&nbsp;<strong><em>Programa IDEA</em></strong>, como una opción válida que permite el estudio de carreras universitarias a aquellas personas que por razones geográficas, laborales o económicas, no tienen acceso a educación superior bajo un método convencional.</p><p class="ql-align-justify"><br></p><p class="ql-align-justify">Los programas de estudio que ofrece, IDEA, están dirigidos a todas las personas que laboran en empresas públicas o privadas, que tengan el deseo de mejorar su eficiencia y productividad por medio del conocimiento de herramientas de informática, gerenciales, contables financieras y administrativas, al mismo tiempo que se concibe como un sistema de pirámide invertida el cual proporciona al alumno desde el inicio de las carreras, cursos de aplicación inmediata.</p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><strong>Educación Superior en toda la República</strong></p><p class="ql-align-justify">El Programa IDEA está integrado por centros de estudio&nbsp;denominados&nbsp;&nbsp;<strong>CEI</strong>, ubicados en diferentes localidades de la República de Guatemala, para facilitarle al alumno el estudio y movilización hasta el lugar en que recibirá las tutorías. Con lo anterior se rompe el concepto tradicional del alumno que asiste a un campus central, y evita de esta manera la saturación de espacio y pérdida de tiempo en el que se incurre al trasladarse de un lugar a otro.</p><p class="ql-align-justify"><br></p><p class="ql-align-center"><strong><em>Un centro de estudios promueve el desarrollo integral de la educación en las diferentes comunidades del país. Asimismo, provee un servicio administrativo y académico de calidad con la finalidad de colaborar con la excelencia académica que distingue a Universidad Galileo.</em></strong></p><p class="ql-align-center"><br></p><p class="ql-align-justify">Actualmente, el Programa cuenta con más de 84 centros de estudio diseminados en toda la República, de los cuales 65 se encuentran abiertos al público en general.</p><p><br></p>	1	2023-08-29 23:04:39	2023-08-29 23:04:39
\.


--
-- Data for Name: archivos; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.archivos (id, activo, descripcion, created_at, updated_at, imagen, url, estado, name_imagen) FROM stdin;
\.


--
-- Data for Name: centros; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.centros (centro, nombre, departamento, municipio, direccion, telefono, encargado, email, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: cursos; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.cursos (id, "Carrera", "Nombre_Curso", "Curso", "Seccion", "Tipoasig", "Periodo", "Pensum", "Ciclo", "No_Asignados", centro, "Jornada", created_at, updated_at, desc_seccion, inicio, fin) FROM stdin;
\.


--
-- Data for Name: especialidades; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.especialidades (id, "Carrera", "Pensum", "Nombre", created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: horarios; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.horarios (id, curso, carrera, seccion, tipoasig, portal, periodo, dia, horaini, horafin, correlativo, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: informacion_academica; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.informacion_academica (id, created_at, updated_at, nombre, icono, descripcion, vence, url) FROM stdin;
\.


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.migrations (id, migration, batch) FROM stdin;
1	2014_10_12_000000_create_users_table	1
2	2014_10_12_100000_create_password_resets_table	1
3	2018_11_23_162127_create_categorias_table	1
4	2020_04_18_071122_create_centros_table	1
5	2020_04_19_012311_create_cursos_table	1
6	2020_05_07_204312_create_archivos_table	1
7	2020_05_12_044642_create_noticias_table	1
8	2020_05_16_202105_create_especialidades_table	1
9	2020_05_27_085013_add_imagen_to_archivos_table	1
10	2020_05_27_194854_create_acerca_table	1
11	2020_05_29_082009_create_horarios_table	1
12	2020_05_30_005050_create_preguntas_table	1
13	2020_06_03_192215_create_periodos_table	1
14	2020_06_05_221550_add_votes_to_desc_seccion_table	1
15	2020_11_20_000330_update_nombre_centros	1
16	2021_01_22_040353_create_permission_tables	1
17	2023_07_17_165120_add_dates_to_cursos_table	1
\.


--
-- Data for Name: model_has_permissions; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.model_has_permissions (permission_id, model_type, model_id) FROM stdin;
\.


--
-- Data for Name: model_has_roles; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.model_has_roles (role_id, model_type, model_id) FROM stdin;
1	App\\User	1
\.


--
-- Data for Name: noticias; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.noticias (id, titulo, descripcion, contenido, visible, created_at, updated_at) FROM stdin;
1	Información importante	Información importante	<p class="ql-align-justify">Estimados Alumnos</p><p class="ql-align-justify">Programa IDEA</p><p class="ql-align-justify">Universidad Galileo</p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify">Para el año 2023 puede realizar su inscripción de manera virtual o de forma presencial en el Centro de Estudios que desee. En caso su inscripción sea de forma virtual, tomar en cuenta lo siguiente: </p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify"><strong>Alumnos de reingreso&nbsp;</strong></p><p class="ql-align-justify">Deben realizar su asignación a través del Portal de Estudiantes Galileo (<a href="http://estudiantes.galileo.edu/" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 123, 255);">estudiantes.galileo.edu</a>).&nbsp;</p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify"><strong>Alumnos de primer ingreso</strong></p><p class="ql-align-justify">A continuación, encontrará el link con la guía de inscripción para asignarse a través del Portal de Admisiones&nbsp;<a href="https://centrosidea.galileo.edu/files/72.pdf" rel="noopener noreferrer" target="_blank" style="color: black;">https://centrosidea.galileo.edu/files/72.pdf</a>&nbsp;</p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify">Cualquier consulta o inconveniente, puede escribir a los correos:</p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><ul><li class="ql-align-justify"><strong style="color: rgb(0, 123, 255);">soporte.idea@galileo.edu</strong></li><li class="ql-align-justify"><strong style="color: rgb(0, 123, 255);">atencionalumnosidea@galileo.edu</strong></li></ul><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify">Agradecemos su comprensión ante dicha situación.</p><p class="ql-align-justify"><span style="color: black;">&nbsp;</span></p><p class="ql-align-justify">Atentamente,</p><p><br></p>	1	2023-08-29 23:02:34	2023-08-29 23:02:34
\.


--
-- Data for Name: password_resets; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.password_resets (email, token, created_at) FROM stdin;
\.


--
-- Data for Name: periodos; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.periodos (carrera, periodo, descripcion, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.permissions (id, name, guard_name, title, description, created_at, updated_at) FROM stdin;
1	registro	web	Registrar usuarios	Formulario para registar nuevos usuarios	2023-08-29 22:58:30	2023-08-29 22:58:30
2	users.index	web	Navegar usuarios	Lista y navega todos los usuarios del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
3	users.show	web	Ver detalle de usuario	Ve en detalle cada usuario del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
4	users.edit	web	Edición de usuarios	Podría editar cualquier dato de un usuario del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
5	users.destroy	web	Eliminar usuario	Podría eliminar cualquier usuario del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
6	roles.index	web	Navegar roles	Lista y navega todos los roles del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
7	roles.show	web	Ver detalle de un rol	Ve en detalle cada rol del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
8	roles.create	web	Creación de roles	Podría crear nuevos roles en el sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
9	roles.edit	web	Edición de roles	Podría editar cualquier dato de un rol del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
10	roles.destroy	web	Eliminar roles	Podría eliminar cualquier rol del sistema	2023-08-29 22:58:30	2023-08-29 22:58:30
11	news	web	Nocicias	Acceso a edicion de noticas	2023-08-29 22:58:30	2023-08-29 22:58:30
12	images	web	Imagenes	Acceso a edicion de imagenes	2023-08-29 22:58:30	2023-08-29 22:58:30
13	files	web	Archivos	Acceso a edicion de archivos	2023-08-29 22:58:30	2023-08-29 22:58:30
14	about	web	Acerca De	Acceso a edicion de información	2023-08-29 22:58:30	2023-08-29 22:58:30
15	contact	web	Contacto	Acceso a edicion de contacto	2023-08-29 22:58:30	2023-08-29 22:58:30
\.


--
-- Data for Name: preguntas; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.preguntas (id, pregunta, respuesta, visible, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: role_has_permissions; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.role_has_permissions (permission_id, role_id) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.roles (id, name, guard_name, title, description, created_at, updated_at) FROM stdin;
1	admin	web	admin	Role de administador total	2023-08-29 22:58:30	2023-08-29 22:58:30
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: userdatabase
--

COPY public.users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at) FROM stdin;
1	Administrador	admin	\N	$2y$10$7VwM32w/8KSe0grjZ7Bnm.OHaNYwmRvYekfPBR4xobDxm45XobTFW	\N	\N	\N
\.

